[package]
name = "map"
version = "0.1.0"
edition = "2021"

[dependencies]
noise = { version = "0.9.0" }
rand = { version = "0.8.5" }
rand_xorshift = { version = "0.3.0" }

[dev-dependencies]
image = { version = "*" }